#!/usr/bin/env bash
cat > .env << EOF

NODE_ENV = $NODE_ENV_PRODUCTION
PORT = $PORT_PRODUCTION

MAGE_URL = $MAGE_URL_PRODUCTION
MAGE_TOKEN = $MAGE_TOKEN_PRODUCTION

CUSTOMER_SERVICE_URL = $CUSTOMER_SERVICE_URL_PRODUCTION

REDIS_CLIENT = $REDIS_CLIENT_PRODUCTION

EOF