name: Node.js CI/CD with GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_CLOUD_RUN_SERVICE: your-service-name
      GOOGLE_CLOUD_REGION: us-central1
      DOCKER_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.GOOGLE_CLOUD_RUN_SERVICE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build and push Docker image
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo ${{ secrets.GCP_SA_KEY }} > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        docker build -t $DOCKER_IMAGE .
        docker push $DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GCP Cloud Run
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: |
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud run deploy ${{ env.GOOGLE_CLOUD_RUN_SERVICE }} --image ${{ env.DOCKER_IMAGE }} --platform managed --region ${{ env.GOOGLE_CLOUD_REGION }} --allow-unauthenticated

    - name: Clean up
      run: rm gcp-key.json
