name: Build and push to GCP

on:
  push:
    branches:
      - main
env:
   GIT_SUBMODULE_STRATEGY: recursive
   FF_NETWORK_PER_BUILD: 1
   DOCKER_DRIVER: overlay2
   DOCKER_HOST: tcp://127.0.0.1:2375
   ROLLOUT_RESOURCE_TYPE: deployment
   DOCKER_TLS_CERTDIR: ""
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
    steps:
      # Set the ENV_FILE_NAME variable based on the branch name.
      - name: Set ENV_FILE_NAME
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            echo "ENV_FILE_NAME=generate-env-dev.sh" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" != "refs/heads/${{ github.base_ref }}" ]]; then
            echo "ENV_FILE_NAME=generate-env-dev.sh" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/${{ github.base_ref }}" ]]; then
            echo "ENV_FILE_NAME=generate-env-production.sh" >> $GITHUB_ENV
          fi
      # Cache the node_modules directory to speed up builds.
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules/
      
       # Generate the environment file.
      - name: Generate environment file
        run: sh ${{ steps.set_env_file_name.outputs.ENV_FILE_NAME }}

      # Log in to the Docker registry.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_keys: ${{ secrets.GOOGLE_SERVICE_ACCOUNT}}
          export_default_credentials: true
      - name: Build and Push Docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT}}
        run: |
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          docker build -t asia-south1-docker.pkg.dev/$GOOGLE_PROJECT/hyuga-catalog-service-test .
          docker push asia-south1-docker.pkg.dev/$GOOGLE_PROJECT/hyuga-catalog-service-test
